#!/usr/bin/python

import subprocess
import optparse
import re

# Get the hostname of the server
HOSTNAME_INFO = """
hostname
"""

# Get the IP Addresses currently bound to the server
IP_INFO = """
ip addr
"""

# Get the route/gateway information on the server
GATEWAY_INFO = """
netstat -nr
"""

# Get the current disk utilization metrics
DISK_INFO = """
df -h
"""

# Get the uptime of the server
SYSTEM_UPTIME = """
uptime
"""

# Get local users
LOCAL_USERS = """
cat /etc/passwd|awk -F: '{print $1}'|sort|uniq
"""

# Here we encapsulate all of the commands we want to run into a list
cmds = [HOSTNAME_INFO, IP_INFO, GATEWAY_INFO, DISK_INFO, SYSTEM_UPTIME, LOCAL_USERS]


def runBash(cmd):
    p = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)
    out = p.stdout.read().strip()
    return out

def runCommands(commands=cmds):
    # List counter
    count=0
    for cmd in cmds:
        count+=1
        print ("---------------------------------------------")
        print (" ")
        subprocess.call(cmd, shell=True)
        print (" ")

runCommands()
